/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createBot {
  name: string;
  token: string;
}

export interface getBot {
  name?: string;
}

export interface removeBot {
  name: string;
}

export interface updateBot {
  bot: {
    name?: string;
    token?: string;
  };
  name: string;
}
