/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface createChat {
  chatId: string;
  name?: string;
}

export interface getChat {
  chatId?: string;
  name?: string;
}

export interface removeChat {
  chatId?: string;
  name?: string;
}

export interface updateChat {
  chat: {
    chatId?: string;
    name?: string;
  };
  chatId?: string;
  name?: string;
}
