/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface appendChat {
  chat: string;
  name: string;
}

export interface createRoute {
  bot: string;
  chats: string[];
  name: string;
}

export interface deleteChat {
  chat: string;
  name: string;
}

export interface getRoute {
  name?: string;
}

export interface removeRoute {
  name: string;
}

export interface updateRoute {
  name: string;
  route: {
    bot?: string;
    name?: string;
  };
}
